### PR TITLE
Fix VirtualizedList multiple selection example shifting focus

### LINKED ISSUE #366: [React Native Gallery -> VirtualizedList]: Unable to select/unselect multiple list items present under "A VirtualizedList with multiple selection support" group in one go using keyboard.
**Repro-Steps:**

- Launch the React Native Gallery app.
- Navigate to VirtualizedList’ button and invoke it.
- Navigate to 'Selection Support' combo box present under "A VirtualizedList with multiple selection support" group and expand it.
- Navigate to 'Multiple' and invoke it.
- Now navigate to list items present under "A VirtualizedList with multiple selection support" and select/unselect and observe focus.

**Actual Result:**

Unable to select/unselect multiple list items present under "A VirtualizedList with multiple selection support" group in one go using keyboard. When user select/unselect any one list item keyboard focus is landing on 'Selection Support' combo box, which is incorrect behaviour.

**Expected Result:**
User should be able to select/unselect multiple list items in one go. When user select/unselect any list item keyboard focus should not redirect to 'Selection Support' combo box. Focus is stay on the selected/unselected list item.

**User Impact:**
Users with motor disabilities who rely on keyboard will face difficulties if keyboard focus redirects to other interactive elements i.e., on 'Selection Support' combo box.

Internal Bug Link: https://dev.azure.com/microsoft/OS/_workitems/edit/47844267

### PR DESCRIPTION
**Pull request by Yajur-Grover**
## Description
Changes VirtualizedList implementation so that focus remains on most recent pressed cell in the virtualized list.

### Why

Resolves #366 

### What
Set refs for each of the cells, and use the useEffect hook and state variable to track most recent pressed item, and set focus to it.

## Screenshots

Focus after pressing item 46:

Before:
https://microsoft-my.sharepoint-df.com/:v:/p/yajurgrover/ETCmQTj-MldLuW8jG_IWEtsBNEn0Xl4qRLeBVLXKvTsp3g?e=BuwCK7&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

After:
https://microsoft-my.sharepoint-df.com/:v:/p/yajurgrover/ET0tSECuWtZHuBjpJir0gFYBh4swEBiJmbssF1q_3I_Znw?e=nZ8Cz5&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

### CODE REVIEW

**Review by TatianaKapos — APPROVED** [review]

**Review by chrisglein — CHANGES_REQUESTED** [review]
1. Can you include a video of the before/after of the behavior here? An image doesn't quite capture it.
2. Do we understand why focus was going to the Picker in the first place?
3. How does this solution scale? I wouldn't expect a developer using VirtualList to have to juggle refs to keep keyboard focus stable.

**Comment by Yajur-Grover** [comment]
> 1. Can you include a video of the before/after of the behavior here? An image doesn't quite capture it.
> 2. Do we understand why focus was going to the Picker in the first place?
> 3. How does this solution scale? I wouldn't expect a developer using VirtualList to have to juggle refs to keep keyboard focus stable.

Looks like the root cause of the issue may be addressed in this PR: https://github.com/microsoft/react-native-gallery/pull/401

**Comment by Yajur-Grover** [comment]
Closing as issue resolved in #401.

**Pull request closed without merging**
