### PR TITLE
Change home page icons from text icons to color icons

### PR DESCRIPTION
**Pull request by chrisglein**
### Why
Part of #405

Here's the home page of the current RN gallery:
image

Here's the home page of the current WinUI gallery:
image

### What

- Added images from WinUI3 gallery
- Adjusted layout to match WinUI3 gallery
- Adjusted categories to match WinUI3 gallery

## Screenshots

image

WinUI3 gallery accessibility tree
image

RN gallery accessibility tree
image

```[tasklist]
### Accessibility
- [x] The element's ControlType requires valid values for SizeOfSet and PositionInSet. (all list items)
- [x] The Name must not include the same text as the LocalizedControlType. (for "Image control" list item)
- [x] The Name property must not include the element's control type. (for "Image control" list item)
- [x] The Name property must not contain any characters in the private Unicode range. (Device info)
```

### CODE REVIEW

**Review by Yajur-Grover — COMMENTED** [review]
Ran fastpass on the home page of the branch and there were some accessibility issues that came up here: 
image

Are you seeing the same locally?

**Comment by chrisglein** [comment]
> Ran fastpass on the home page of the branch and there were some accessibility issues that came up here: 
> Are you seeing the same locally?

Hadn't run it yet but I'm seeing them now. I'll dig into these. I was trying to mirror the WinUI3 gallery accessibility, so I'll see how they handled these.

**Comment by chrisglein** [comment]
> > Ran fastpass on the home page of the branch and there were some accessibility issues that came up here:
> > Are you seeing the same locally?
> 
> Hadn't run it yet but I'm seeing them now. I'll dig into these. I was trying to mirror the WinUI3 gallery accessibility, so I'll see how they handled these.
> 
> Edit: Added tasklist in issue description to track

Okay, pushed commits to address these and have it run clean.
- The "Image" name one triggers in WinUI3 Gallery too. I opted to workaround by using a different word ("Graphic"), which is not great but quiets the tool. I'll follow up to figure out if there's a way to suppress that warning on a specific item. Alternatively, we could live with the warning.
- I changed the layered image+text to show as an "image", because that's how the eye sees them.
- The last problem was that it didn't like the "list item" types because they were missing information about position/order. I reverted to "button" for now (what it was before). Will need some digging to figure out if list item is implemented fully or not.

**Review by chiaramooney — APPROVED** [review]
👍

**Pull request merged**
