### PR TITLE
Add page for react-native-track-player component

### PR DESCRIPTION
**Pull request by tritao**
ApplicationFrameHost_A17jzrfwFO

### CODE REVIEW

**Review by chiaramooney — APPROVED** [review]
Looks good

**Comment by tritao** [comment]
I am on vacation this week but I'll rebase this ASAP next week.

**Comment by tritao** [comment]
Ready to merge.

**Comment by tritao** [comment]
@chiaramooney Any chance this could be merged soon? 

I have some others PR to process and there will be conflicts after this one is merged, so I'd appreciate if this one could be merged first.

**Pull request merged**
