### PR TITLE
Change colors of 'Open Popup' buttons on Flyout page to work in High-Contrast theme modes

### PR DESCRIPTION
**Pull request by YajurG**
## Description

Change colors of 'Open Popup' buttons on Flyout page to work in High-Contrast theme modes

### Why

What is the motivation for this change? Add a few sentences describing the context and overall goals of the pull request's commits.

Resolves [#308]

### What

Changed background color of TouchableHighlight components so that button text is visible in both normal and high-contrast themes.

Note: temporary fix as currently have just changed the color. Trying to use `PlatformColor` property to resolve this issue but running into some errors on Gallery when trying to implement.

## Screenshots

In Desert Contrast theme

Before:
image

After:
image

### CODE REVIEW

**Comment by AgneLukoseviciute** [comment]
Could you fix up the upper sticker as well while you're at it? 
image

**Review by jonthysell — APPROVED** [review]

**Comment by chrisglein** [comment]
> Note: temporary fix as currently have just changed the color. Trying to use PlatformColor property to resolve this issue but running into some errors on Gallery when trying to implement.

What were those errors? Can you open a tracking issue for the non-temporary fix?

**Comment by YajurG** [comment]
> What were those errors? Can you open a tracking issue for the non-temporary fix?

Will repro and post in a separate issue

**Review by TatianaKapos — APPROVED** [review]
LTGM! I would just double check that snapshot tests don't need to be updated again with the new commits :)

**Comment by YajurG** [comment]
> Could you fix up the upper sticker as well while you're at it? image

Updated page in desert contrast theme:
image

**Pull request merged**
