### PR TITLE
Add page for react-native-sensitive-info

### PR DESCRIPTION
**Pull request by tritao**
ApplicationFrameHost_ciGtFgFpqt

### CODE REVIEW

**Comment by tritao** [comment]
Ready for review.

**Review by chiaramooney — APPROVED** [review]
👍 looks great. Could you add a screenshot of the page to the PR description?

**Comment by tritao** [comment]
Sure, updated with screenshot.

**Comment by chiaramooney** [comment]
@tritao Looks like there are some merge conflicts that need to be resolved before I can merge your changes. Could you resolve those?

**Pull request merged**
